version: '3'

services:

networks:
  Book_Homestay_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
#子网: 172.20.0.0/16
#网络地址: 172.20.0.0 (子网中的第一个地址，不可用)
#广播地址: 172.20.255.255 (子网中的最后一个地址，不可用)
#可用主机范围: 172.20.0.1 到 172.20.255.254

  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - Book_Homestay_net
    depends_on:
      - Book_Homestay

Book_Homestay:
    image: lyumikael/gomodd:v1.20.3
    container_name: Book_Homestay
    environment:
      TZ: Asia/Shanghai #时区
      GOPROXY: https://goproxy.cn,direct  
    working_dir: /go/Book_Homestay #容器内的工作目录
    volumes:
      - .:/go/Book_Homestay #挂载
    restart: always  #发送意外崩溃自动重启
    networks:
      - Book_Homestay_net




