// Code generated by goctl. DO NOT EDIT.
// Source: travel.proto

package homestay

import (
	"context"

	"Book_Homestay/app/travel/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BusinessListReq           = pb.BusinessListReq
	BusinessListResp          = pb.BusinessListResp
	BussinessReq              = pb.BussinessReq
	BussinessResp             = pb.BussinessResp
	CommentListReq            = pb.CommentListReq
	CommentListResp           = pb.CommentListResp
	CommentListbyIdReq        = pb.CommentListbyIdReq
	CommentListbyIdResp       = pb.CommentListbyIdResp
	GoodbossReq               = pb.GoodbossReq
	GoodbossResp              = pb.GoodbossResp
	GuessListReq              = pb.GuessListReq
	GuessListResp             = pb.GuessListResp
	Homestay                  = pb.Homestay
	HomestayBusinessBoss      = pb.HomestayBusinessBoss
	HomestayComment           = pb.HomestayComment
	HomestayDetailReq         = pb.HomestayDetailReq
	HomestayDetailResp        = pb.HomestayDetailResp
	HomestayListReq           = pb.HomestayListReq
	HomestayListResp          = pb.HomestayListResp
	HomestaybussinesslistReq  = pb.HomestaybussinesslistReq
	HomestaybussinesslistResp = pb.HomestaybussinesslistResp

	HomestayZrpcClient interface {
		HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error)
		HomestayList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayListResp, error)
		BusinessList(ctx context.Context, in *BusinessListReq, opts ...grpc.CallOption) (*BusinessListResp, error)
		GuessList(ctx context.Context, in *GuessListReq, opts ...grpc.CallOption) (*GuessListResp, error)
	}

	defaultHomestayZrpcClient struct {
		cli zrpc.Client
	}
)

func NewHomestayZrpcClient(cli zrpc.Client) HomestayZrpcClient {
	return &defaultHomestayZrpcClient{
		cli: cli,
	}
}

func (m *defaultHomestayZrpcClient) HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error) {
	client := pb.NewHomestayClient(m.cli.Conn())
	return client.HomestayDetail(ctx, in, opts...)
}

func (m *defaultHomestayZrpcClient) HomestayList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayListResp, error) {
	client := pb.NewHomestayClient(m.cli.Conn())
	return client.HomestayList(ctx, in, opts...)
}

func (m *defaultHomestayZrpcClient) BusinessList(ctx context.Context, in *BusinessListReq, opts ...grpc.CallOption) (*BusinessListResp, error) {
	client := pb.NewHomestayClient(m.cli.Conn())
	return client.BusinessList(ctx, in, opts...)
}

func (m *defaultHomestayZrpcClient) GuessList(ctx context.Context, in *GuessListReq, opts ...grpc.CallOption) (*GuessListResp, error) {
	client := pb.NewHomestayClient(m.cli.Conn())
	return client.GuessList(ctx, in, opts...)
}
