// Code generated by goctl. DO NOT EDIT.
// Source: travel.proto

package server

import (
	"context"

	"Book_Homestay/app/travel/cmd/rpc/internal/logic/homestaybussiness"
	"Book_Homestay/app/travel/cmd/rpc/internal/svc"
	"Book_Homestay/app/travel/cmd/rpc/pb"
)

type HomestaybussinessServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedHomestaybussinessServer
}

func NewHomestaybussinessServer(svcCtx *svc.ServiceContext) *HomestaybussinessServer {
	return &HomestaybussinessServer{
		svcCtx: svcCtx,
	}
}

func (s *HomestaybussinessServer) Goodboss(ctx context.Context, in *pb.GoodbossReq) (*pb.GoodbossResp, error) {
	l := homestaybussinesslogic.NewGoodbossLogic(ctx, s.svcCtx)
	return l.Goodboss(in)
}

func (s *HomestaybussinessServer) Homestaybussinessdetail(ctx context.Context, in *pb.BussinessReq) (*pb.BussinessResp, error) {
	l := homestaybussinesslogic.NewHomestaybussinessdetailLogic(ctx, s.svcCtx)
	return l.Homestaybussinessdetail(in)
}

func (s *HomestaybussinessServer) Homestaybussinesslist(ctx context.Context, in *pb.HomestaybussinesslistReq) (*pb.HomestaybussinesslistResp, error) {
	l := homestaybussinesslogic.NewHomestaybussinesslistLogic(ctx, s.svcCtx)
	return l.Homestaybussinesslist(in)
}
