// Code generated by goctl. DO NOT EDIT.
// Source: travel.proto

package server

import (
	"context"

	"Book_Homestay/app/travel/cmd/rpc/internal/logic/homestaycomment"
	"Book_Homestay/app/travel/cmd/rpc/internal/svc"
	"Book_Homestay/app/travel/cmd/rpc/pb"
)

type HomestaycommentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedHomestaycommentServer
}

func NewHomestaycommentServer(svcCtx *svc.ServiceContext) *HomestaycommentServer {
	return &HomestaycommentServer{
		svcCtx: svcCtx,
	}
}

func (s *HomestaycommentServer) CommentListbyId(ctx context.Context, in *pb.CommentListbyIdReq) (*pb.CommentListbyIdResp, error) {
	l := homestaycommentlogic.NewCommentListbyIdLogic(ctx, s.svcCtx)
	return l.CommentListbyId(in)
}

func (s *HomestaycommentServer) CommentList(ctx context.Context, in *pb.CommentListReq) (*pb.CommentListResp, error) {
	l := homestaycommentlogic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
