// Code generated by goctl. DO NOT EDIT.
// Source: travel.proto

package homestaycomment

import (
	"context"

	"Book_Homestay/app/travel/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BusinessListReq           = pb.BusinessListReq
	BusinessListResp          = pb.BusinessListResp
	BussinessReq              = pb.BussinessReq
	BussinessResp             = pb.BussinessResp
	CommentListReq            = pb.CommentListReq
	CommentListResp           = pb.CommentListResp
	CommentListbyIdReq        = pb.CommentListbyIdReq
	CommentListbyIdResp       = pb.CommentListbyIdResp
	GoodbossReq               = pb.GoodbossReq
	GoodbossResp              = pb.GoodbossResp
	GuessListReq              = pb.GuessListReq
	GuessListResp             = pb.GuessListResp
	Homestay                  = pb.Homestay
	HomestayBusinessBoss      = pb.HomestayBusinessBoss
	HomestayComment           = pb.HomestayComment
	HomestayDetailReq         = pb.HomestayDetailReq
	HomestayDetailResp        = pb.HomestayDetailResp
	HomestayListReq           = pb.HomestayListReq
	HomestayListResp          = pb.HomestayListResp
	HomestaybussinesslistReq  = pb.HomestaybussinesslistReq
	HomestaybussinesslistResp = pb.HomestaybussinesslistResp

	Homestaycomment interface {
		CommentListbyId(ctx context.Context, in *CommentListbyIdReq, opts ...grpc.CallOption) (*CommentListbyIdResp, error)
		CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error)
	}

	defaultHomestaycomment struct {
		cli zrpc.Client
	}
)

func NewHomestaycomment(cli zrpc.Client) Homestaycomment {
	return &defaultHomestaycomment{
		cli: cli,
	}
}

func (m *defaultHomestaycomment) CommentListbyId(ctx context.Context, in *CommentListbyIdReq, opts ...grpc.CallOption) (*CommentListbyIdResp, error) {
	client := pb.NewHomestaycommentClient(m.cli.Conn())
	return client.CommentListbyId(ctx, in, opts...)
}

func (m *defaultHomestaycomment) CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error) {
	client := pb.NewHomestaycommentClient(m.cli.Conn())
	return client.CommentList(ctx, in, opts...)
}
