// Code generated by goctl. DO NOT EDIT.
// Source: travel.proto

package homestaybussiness

import (
	"context"

	"Book_Homestay/app/travel/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BusinessListReq           = pb.BusinessListReq
	BusinessListResp          = pb.BusinessListResp
	BussinessReq              = pb.BussinessReq
	BussinessResp             = pb.BussinessResp
	CommentListReq            = pb.CommentListReq
	CommentListResp           = pb.CommentListResp
	CommentListbyIdReq        = pb.CommentListbyIdReq
	CommentListbyIdResp       = pb.CommentListbyIdResp
	GoodbossReq               = pb.GoodbossReq
	GoodbossResp              = pb.GoodbossResp
	GuessListReq              = pb.GuessListReq
	GuessListResp             = pb.GuessListResp
	Homestay                  = pb.Homestay
	HomestayBusinessBoss      = pb.HomestayBusinessBoss
	HomestayComment           = pb.HomestayComment
	HomestayDetailReq         = pb.HomestayDetailReq
	HomestayDetailResp        = pb.HomestayDetailResp
	HomestayListReq           = pb.HomestayListReq
	HomestayListResp          = pb.HomestayListResp
	HomestaybussinesslistReq  = pb.HomestaybussinesslistReq
	HomestaybussinesslistResp = pb.HomestaybussinesslistResp

	Homestaybussiness interface {
		Goodboss(ctx context.Context, in *GoodbossReq, opts ...grpc.CallOption) (*GoodbossResp, error)
		Homestaybussinessdetail(ctx context.Context, in *BussinessReq, opts ...grpc.CallOption) (*BussinessResp, error)
		Homestaybussinesslist(ctx context.Context, in *HomestaybussinesslistReq, opts ...grpc.CallOption) (*HomestaybussinesslistResp, error)
	}

	defaultHomestaybussiness struct {
		cli zrpc.Client
	}
)

func NewHomestaybussiness(cli zrpc.Client) Homestaybussiness {
	return &defaultHomestaybussiness{
		cli: cli,
	}
}

func (m *defaultHomestaybussiness) Goodboss(ctx context.Context, in *GoodbossReq, opts ...grpc.CallOption) (*GoodbossResp, error) {
	client := pb.NewHomestaybussinessClient(m.cli.Conn())
	return client.Goodboss(ctx, in, opts...)
}

func (m *defaultHomestaybussiness) Homestaybussinessdetail(ctx context.Context, in *BussinessReq, opts ...grpc.CallOption) (*BussinessResp, error) {
	client := pb.NewHomestaybussinessClient(m.cli.Conn())
	return client.Homestaybussinessdetail(ctx, in, opts...)
}

func (m *defaultHomestaybussiness) Homestaybussinesslist(ctx context.Context, in *HomestaybussinesslistReq, opts ...grpc.CallOption) (*HomestaybussinesslistResp, error) {
	client := pb.NewHomestaybussinessClient(m.cli.Conn())
	return client.Homestaybussinesslist(ctx, in, opts...)
}
