// Code generated by goctl. DO NOT EDIT.
// Source: travel.proto

package server

import (
	"context"

	"Book_Homestay/app/travel/cmd/rpc/internal/logic/homestay"
	"Book_Homestay/app/travel/cmd/rpc/internal/svc"
	"Book_Homestay/app/travel/cmd/rpc/pb"
)

type HomestayServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedHomestayServer
}

func NewHomestayServer(svcCtx *svc.ServiceContext) *HomestayServer {
	return &HomestayServer{
		svcCtx: svcCtx,
	}
}

func (s *HomestayServer) HomestayDetail(ctx context.Context, in *pb.HomestayDetailReq) (*pb.HomestayDetailResp, error) {
	l := homestaylogic.NewHomestayDetailLogic(ctx, s.svcCtx)
	return l.HomestayDetail(in)
}

func (s *HomestayServer) HomestayList(ctx context.Context, in *pb.HomestayListReq) (*pb.HomestayListResp, error) {
	l := homestaylogic.NewHomestayListLogic(ctx, s.svcCtx)
	return l.HomestayList(in)
}

func (s *HomestayServer) BusinessList(ctx context.Context, in *pb.BusinessListReq) (*pb.BusinessListResp, error) {
	l := homestaylogic.NewBusinessListLogic(ctx, s.svcCtx)
	return l.BusinessList(in)
}

func (s *HomestayServer) GuessList(ctx context.Context, in *pb.GuessListReq) (*pb.GuessListResp, error) {
	l := homestaylogic.NewGuessListLogic(ctx, s.svcCtx)
	return l.GuessList(in)
}
