// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"` //jwt过期时间
	RefreshAfter int64  `json:"refreshAfter"` //刷新的时间间隔
}

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"` //电话
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"` //头像
	Info     string `json:"info"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type WXMiniAuthReq struct {
	Code          string `json:"code"`          //登录凭证（code）
	IV            string `json:"iv"`            //初始向量，为16字节base64字符串
	EncryptedData string `json:"encryptedData"` //加密后的密文，使用base64编码
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
